### ISSUE TITLE
startInstance system.adapter.mygekko.0: required adapter "request" not found!

### ISSUE THREAD

**Issue by merlin2533** [Vogelbecker/ioBroker.mygekko#1]
Adapter Installation:
Erfolgreich ohne Probleme in Version 0.0.2

Leider wird beim Start des Adapter folgender Fehler ausgeworfen:
startInstance system.adapter.mygekko.0: required adapter "request" not found!

NPM Install von Request ohne Erfolg.

Umgebung ist ein Raspi 4 mit IoBroker im neusten Release

**Comment by merlin2533** [comment]
$ ./iobroker url "https://github.com/Vogelbecker/ioBroker.mygekko.git"
install https://github.com/Vogelbecker/ioBroker.mygekko/tarball/88fe1be7e8e3d84c17163b61a179d9bbee075e74
NPM version: 6.14.5
npm install https://github.com/Vogelbecker/ioBroker.mygekko/tarball/88fe1be7e8e3d84c17163b61a179d9bbee075e74 --loglevel error --prefix "/opt/iobroker" (System call)
Package pangocairo was not found in the pkg-config search path.Perhaps you should add the directory containing `pangocairo.pc'to the PKG_CONFIG_PATH environment variableNo package 'pangocairo' foundgyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp
 ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)gyp ERR! stack     at ChildProcess.emit (events.js:315:20)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.58-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/iobroker/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"gyp ERR! cwd /opt/iobroker/node_modules/canvasgyp ERR! node -v v12.18.1gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok 
node-pre-gyp ERR! build error node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/iobroker/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)node-pre-gyp ERR! System Linux 4.19.58-v7l+node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"node-pre-gyp ERR! cwd /opt/iobroker/node_modules/canvasnode-pre-gyp ERR! node -v v12.18.1node-pre-gyp ERR! node-pre-gyp -v v0.11.0node-pre-gyp ERR! not ok

**Comment by Vogelbecker** [comment]
Hatte hier vermutlich eine alte package-lock.json mit hochgeladen.

Kannst du nochmal die aktuelle Version installieren und es erneut probieren?

**Comment by merlin2533** [comment]
works fine.
